### PR TITLE
Increase job time for FastQC and Fastq screen

### PR DESCRIPTION
**Pull request by matrulda**
Solves issue where slurm job for FastQC would be cancelled due to time limit. I increased the time for fastq screen as well, since these jobs also takes longer with larger data sizes. 

It would be more optimal to have a solution like nf-core pipelines have, where processes failing with this error code are re-run with incrementally increasing compute resources. I do however see no reason to implement this in this pipeline, since the long-term plan is to use switch to the nf-core/seqinspector.

### CODE REVIEW

**Review by Aratz — APPROVED** [review]
Looks good to me :+1: 

Although I have a few comments/questions:
- will 6h be enough or do we want to increase it even more? We don't really have any scheduling issues on Miarka atm to we could go even higher.
- Would it maybe be better to have this config in miarka-provision and thus avoid having to do PRs in seqreports, sequencing-report-service and miarka-provision every time we want update the config?

**Comment by matrulda** [comment]
Thanks for the review. Good points! 
1. Yeah, we could increase it even more. I think this should work for quite a while though. 25B is the largest flowcell on the NovaSeq X and we have already processed other ones without issues (not that many though). One issue with having a too generous timelimit is that jobs can become blocked due to maintenance. However that's mainly an issue when the timelimit it set to > 24 hours. Perhaps I should change it to 12 hours? 
2. Yes, I agree that this is cumbersome. My vision is that we in the future should able to add/overwrite config variables via the service. So that the service basically will run `nextflow run -c <config from request> -c <config deployed by miarka-provision> -c <default pipeline config> [...]`
EDIT: Perhaps this is already a thing with the version that supports arbitrary pipelines?

**Comment by Aratz** [comment]
1. Yeah 12h sounds like a good compromise :+1:
2. I see, yes as of now one can add extra arguments but not send an extra configuration file. So what one could do is place the new config file on Miarka and specify its path as an extra argument

**Comment by matrulda** [comment]
Nice, we should look into that. I can create a ticket. 

Also, the timelimit is now increased to 12h.

**Pull request merged**
