### PR TITLE
Update dsl2 syntax

### PR DESCRIPTION
**Pull request by mahesh-panchal**
Updated syntax to fit current DSL2 conventions and added some comments. 

This is untested. I no longer have a project on Uppmax with the test data.

### CODE REVIEW

**Review by matrulda — CHANGES_REQUESTED** [review]
Thanks for the PR, @mahesh-panchal ! 
I get the following error when trying to run from this branch: 
```
Unqualified input value declaration has been deprecated - replace `tuple project,..` with `tuple val(project),..`
```
Sorry for not having test data available. 😬 Hopefully we will be able to add that (and automatic tests) in a not too far away future.

**Comment by mahesh-panchal** [comment]
> I get the following error when trying to run from this branch:
> 
> ```
> Unqualified input value declaration has been deprecated - replace `tuple project,..` with `tuple val(project),..`
> ```

OK. I think I took care of it. 

> Sorry for not having test data available. 😬 Hopefully we will be able to add that (and automatic tests) in a not too far away future.

If you do need help with this, feel free to pass some of this on to me.

**Comment by matrulda** [comment]
> If you do need help with this, feel free to pass some of this on to me.

Thank you!

**Review by matrulda — APPROVED** [review]
Great, works now. 👍

**Pull request merged**
