### PR TITLE
Add slurm profile to config

### PR DESCRIPTION
**Pull request by matrulda**
This should make it possible to run the pipeline using slurm. 

I'm planning to follow this PR up with another one that removes the Clarity integration. We barely make use of it and it causes troubles when you can't connect to a Clarity LIMS (like the situation is for us on Uppmax cluster Irma).

### CODE REVIEW

**Comment by matrulda** [comment]
@johandahlberg As far as I can see, you don't really have to specify max resources when using the slurm executor, I think it's done automatically. Do you think it make sense to call the profile uppmax or does it make more sense to call it `irma`?

**Comment by johandahlberg** [comment]
I think it should be `irma`.

**Comment by johandahlberg** [comment]
If I understand the nextflow docs correctly, what you set in the profile is the default config. And then you set for each separate process what resources that needs. To having 1 cpu (with 8 GB of RAM) should be sufficient for most or all of our processes here.

**Comment by matrulda** [comment]
@johandahlberg :+1: I'll change it to `irma`. So do you think the resource specification is good as it is?

**Pull request merged**
